### PR TITLE
Add support for PHP 8.0

### PR DESCRIPTION
**Pull request by boesing**

### CODE REVIEW

**Review by michalbundyra — APPROVED** [review]

**Review by weierophinney — CHANGES_REQUESTED** [review]
Um... we need to test against PHP 8 as well, which means a `.travis.yml` entry...

**Comment by michalbundyra** [comment]
@weierophinney 

> Um... we need to test against PHP 8 as well, which means a .travis.yml entry...

It's already there: 

https://github.com/mezzio/mezzio-cors/blob/1.0.x/.travis.yml#L29-L39

**Comment by weierophinney** [comment]
> It's already there:

My bad! I assumed it wasn't, as this patch was adding the constraint!

**Review by weierophinney — APPROVED** [review]
:ship:

**Pull request merged**
